### ISSUE TITLE
Update Apiary privacy policy for mobile app

### ISSUE THREAD

**Issue by evan10s** [RoboJackets/apiary-mobile#28]
- [ ] Add a section for additional data we collect if you use the mobile app (user agent, Sentry, etc.)
- [ ] Clarify that any user may contact us to request deletion of their data

**Comment by evan10s** [comment]
See also https://support.google.com/googleplay/android-developer/answer/10144311#safetysection

**Comment by kberzinch** [comment]
Implemented as part of https://github.com/RoboJackets/apiary/pull/2125
